### ISSUE TITLE
sleap v1.6.2 not utilizing cuda GPU during model training.

### ISSUE THREAD

**Issue by dankunk** [talmolab/sleap#2663]
Not sure if this is a true bug or if it belongs in the discussion. But my issue is that SLEAP v1.6.2 installed with the uv package manager is not utilizing the nvidia GPU that is present on my machine. Instead it seems to be utilizing the CPU.

I am utilizing SLEAP 1.6.2 rather than 1.6.1 as I had an issue as mentioned in #2636 where my sleap files would not load after reducing some of the nodes in my skeleton.

When trying to train a unet model with the default settings. It seems like it knows my GPU is present, but still the utilization/VRAM of the GPU is pretty much zero during training while my CPU and RAM are seemingly being utilized. 

Here is the code that I ran during training
```
PS C:\Users\nalamlab\desktop\SLEAP_TRAINING\diet> sleap

╭────────────────────────────────────────────────────────────╮
│                                                            │
│              ____  _     _____    _    ____                │
│             / ___|| |   | ____|  / \  |  _ \               │
│             \___ \| |   |  _|   / _ \ | |_) |              │
│              ___) | |___| |___ / ___ \|  __/               │
│             |____/|_____|_____/_/   \_\_|                  │
│                                                            │
│             Social LEAP Estimates Animal Poses             │
│                                                            │
│      SLEAP v1.6.2 | sleap-io v0.6.5 | sleap-nn v0.1.3      │
│                Windows 11 | Python 3.13.12                 │
│                                                            │
│                Docs: https://docs.sleap.ai                 │
│   Support: https://github.com/talmolab/sleap/discussions   │
│                                                            │
│                      Happy SLEAPing!                       │
│                                                            │
╰────────────────────────────────────────────────────────────╯

Launching GUI...
Restoring GUI state...
Saving config: C:\Users\nalamlab\.sleap\1.6.2\preferences.yaml
Saving config: C:\Users\nalamlab\.sleap\1.6.2\preferences.yaml
Saving config: C:\Users\nalamlab\.sleap\1.6.2\preferences.yaml
Saving config: C:\Users\nalamlab\.sleap\1.6.2\preferences.yaml
Saving config: C:\Users\nalamlab\.sleap\1.6.2\preferences.yaml
Saving config: C:\Users\nalamlab\.sleap\1.6.2\preferences.yaml
Resetting monitor window.
Polling: C:/Users/nalamlab/Desktop/SLEAP_TRAINING/diet/models/fast_unet\viz\validation.*.png
Start training centroid...
['sleap', 'train', '--config-name', '260324_143805_config', '--config-dir', 'C:\\Users\\nalamlab\\AppData\\Local\\Temp\\tmpeumjbve0']
2026-03-24 14:38:16 | Input config:
2026-03-24 14:38:16 |
data_config:
  train_labels_path:
  - C:/Users/nalamlab/Desktop/SLEAP_TRAINING/diet/Rpadi_diet_reducedSkeleton_labels.v001.slp
  val_labels_path: null
  validation_fraction: 0.1
  use_same_data_for_val: false
  test_file_path: null
  provider: LabelsReader
  user_instances_only: true
  data_pipeline_fw: torch_dataset_cache_img_memory
  cache_img_path: null
  use_existing_imgs: false
  delete_cache_imgs_after_training: true
  parallel_caching: true
  cache_workers: 0
  preprocessing:
    ensure_rgb: false
    ensure_grayscale: false
    max_height: null
    max_width: null
    scale: 0.25
    crop_size: null
    min_crop_size: 100
    crop_padding: null
  use_augmentations_train: true
  augmentation_config:
    intensity:
      uniform_noise_min: 0.0
      uniform_noise_max: 1.0
      uniform_noise_p: 0.0
      gaussian_noise_mean: 5.0
      gaussian_noise_std: 1.0
      gaussian_noise_p: 0.0
      contrast_min: 0.5
      contrast_max: 2.0
      contrast_p: 0.0
      brightness_min: 0.0
      brightness_max: 2.0
      brightness_p: 0.0
    geometric:
      rotation_min: -180.0
      rotation_max: 180.0
      rotation_p: 1.0
      scale_min: 0.9
      scale_max: 1.1
      scale_p: 1.0
      translate_width: 0.0
      translate_height: 0.0
      translate_p: null
      affine_p: 0.0
      erase_scale_min: 0.0001
      erase_scale_max: 0.01
      erase_ratio_min: 1.0
      erase_ratio_max: 1.0
      erase_p: 0.0
      mixup_lambda_min: 0.01
      mixup_lambda_max: 0.05
      mixup_p: 0.0
  use_negative_frames: false
  negative_loss_weight: 1.0
  skeletons: null
model_config:
  init_weights: default
  pretrained_backbone_weights: null
  pretrained_head_weights: null
  backbone_config:
    unet:
      in_channels: 1
      kernel_size: 3
      filters: 16
      filters_rate: 2.0
      max_stride: 16
      stem_stride: null
      middle_block: true
      up_interpolate: true
      stacks: 1
      convs_per_block: 2
      output_stride: 2
    convnext: null
    swint: null
  head_configs:
    single_instance: null
    centroid:
      confmaps:
        anchor_part: ab
        sigma: 5.0
        output_stride: 2
    centered_instance: null
    bottomup: null
    multi_class_bottomup: null
    multi_class_topdown: null
  total_params: null
trainer_config:
  train_data_loader:
    batch_size: 4
    num_workers: 5
    shuffle: true
  val_data_loader:
    batch_size: 4
    num_workers: 5
    shuffle: false
  model_ckpt:
    save_top_k: 1
    save_last: false
  trainer_devices: null
  trainer_device_indices: null
  trainer_accelerator: cuda
  profiler: null
  trainer_strategy: auto
  enable_progress_bar: true
  min_train_steps_per_epoch: 200
  train_steps_per_epoch: null
  visualize_preds_during_training: true
  keep_viz: false
  max_epochs: 200
  seed: null
  use_wandb: false
  save_ckpt: true
  ckpt_dir: C:/Users/nalamlab/Desktop/SLEAP_TRAINING/diet/models
  run_name: fast_unet
  resume_ckpt_path: null
  wandb:
    entity: null
    project: null
    name: null
    save_viz_imgs_wandb: false
    api_key: null
    wandb_mode: null
    prv_runid: null
    group: null
    current_run_id: null
    viz_enabled: true
    viz_boxes: false
    viz_masks: false
    viz_box_size: 5.0
    viz_confmap_threshold: 0.1
    log_viz_table: false
    delete_local_logs: null
  optimizer_name: Adam
  optimizer:
    lr: 0.0001
    amsgrad: false
  lr_scheduler:
    step_lr: null
    reduce_lr_on_plateau:
      threshold: 1.0e-06
      threshold_mode: abs
      cooldown: 3
      patience: 5
      factor: 0.5
      min_lr: 1.0e-08
    cosine_annealing_warmup: null
    linear_warmup_linear_decay: null
  early_stopping:
    min_delta: 1.0e-08
    patience: 10
    stop_training_on_plateau: true
  online_hard_keypoint_mining:
    online_mining: false
    hard_to_easy_ratio: 2.0
    min_hard_keypoints: 2
    max_hard_keypoints: null
    loss_scale: 5.0
  zmq:
    controller_port: 9000
    controller_polling_timeout: 10
    publish_port: 9001
  eval:
    enabled: true
    frequency: 1
    oks_stddev: 0.025
    oks_scale: null
    match_threshold: 50.0
name: ''
description: ''
sleap_nn_version: 0.1.3
filename: ''

2026-03-24 14:38:16 | Started training at: 2026-03-24 14:38:16.971878
2026-03-24 14:38:16 | sleap-nn 0.1.3 | Python 3.13.12 | PyTorch 2.9.0+cu129 | CUDA 12.9 | 1 GPU(s)
2026-03-24 14:38:17 | Creating train-val split...
2026-03-24 14:38:23 | # Train Labeled frames: 231
2026-03-24 14:38:23 | # Val Labeled frames: 25
2026-03-24 14:38:23 | Setting up config...
2026-03-24 14:38:24 | Setting up for training...
2026-03-24 14:38:24 | Setting up model ckpt dir: `C:/Users/nalamlab/Desktop/SLEAP_TRAINING/diet/models/fast_unet`...
2026-03-24 14:38:26 | Setting up visualization train and val datasets...
2026-03-24 14:38:26 | Setting up Trainer...
2026-03-24 14:38:26 | Setting up callbacks and loggers...
2026-03-24 14:38:26 | Training controller subscribed to: tcp://127.0.0.1:9000 (topic: )
2026-03-24 14:38:26 | ProgressReporterZMQ publishing to tcp://127.0.0.1:9001 for ''
2026-03-24 14:38:26 | Trainer devices: auto
INFO: GPU available: True (cuda), used: True
INFO:lightning.pytorch.utilities.rank_zero:GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
INFO:lightning.pytorch.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO: 💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
INFO:lightning.pytorch.utilities.rank_zero:💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
2026-03-24 14:38:26 | Using in-memory caching with 5 DataLoader workers on Windows. Memory usage may be significantly higher than estimated (~1.9 GB extra) due to spawn-based multiprocessing. Consider using disk caching or num_workers=0 for large datasets.
2026-03-24 14:38:26 | Caching 231 images to memory...
2026-03-24 14:38:45 | Caching complete.
2026-03-24 14:38:45 | Caching 25 images to memory...
2026-03-24 14:38:48 | Caching complete.
2026-03-24 14:38:50 | Training on 1 device(s)
2026-03-24 14:38:50 | Training on cuda:0 accelerator
2026-03-24 14:38:50 | Setting up lightning module for centroid model...
2026-03-24 14:38:50 | Backbone model: UNet(
  (encoders): ModuleList(
    (0): Encoder(
      (encoder_stack): ModuleList(
        (0): SimpleConvBlock(
          (blocks): Sequential(
            (stack0_enc0_conv0): Conv2d(1, 16, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_enc0_act0_relu): ReLU()
            (stack0_enc0_conv1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_enc0_act1_relu): ReLU()
          )
        )
        (1): SimpleConvBlock(
          (blocks): Sequential(
            (stack0_enc1_pool): MaxPool2dWithSamePadding(kernel_size=2, stride=2, padding=same, dilation=1, ceil_mode=False)
            (stack0_enc1_conv0): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_enc1_act0_relu): ReLU()
            (stack0_enc1_conv1): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_enc1_act1_relu): ReLU()
          )
        )
        (2): SimpleConvBlock(
          (blocks): Sequential(
            (stack0_enc2_pool): MaxPool2dWithSamePadding(kernel_size=2, stride=2, padding=same, dilation=1, ceil_mode=False)
            (stack0_enc2_conv0): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_enc2_act0_relu): ReLU()
            (stack0_enc2_conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_enc2_act1_relu): ReLU()
          )
        )
        (3): SimpleConvBlock(
          (blocks): Sequential(
            (stack0_enc3_pool): MaxPool2dWithSamePadding(kernel_size=2, stride=2, padding=same, dilation=1, ceil_mode=False)
            (stack0_enc3_conv0): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_enc3_act0_relu): ReLU()
            (stack0_enc3_conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_enc3_act1_relu): ReLU()
          )
        )
        (4): Sequential(
          (stack0_enc4_last_pool): MaxPool2dWithSamePadding(kernel_size=2, stride=2, padding=same, dilation=1, ceil_mode=False)
        )
      )
    )
  )
  (decoders): ModuleList(
    (0): Decoder(
      (decoder_stack): ModuleList(
        (0): SimpleUpsamplingBlock(
          (blocks): Sequential(
            (stack0_dec0_s16_to_s8_interp_bilinear): Upsample(scale_factor=2.0, mode='bilinear')
            (stack0_dec0_s16_to_s8_refine_conv0): Conv2d(384, 128, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_dec0_s16_to_s8_refine_conv0_act_relu): ReLU()
            (stack0_dec0_s16_to_s8_refine_conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_dec0_s16_to_s8_refine_conv1_act_relu): ReLU()
          )
        )
        (1): SimpleUpsamplingBlock(
          (blocks): Sequential(
            (stack0_dec1_s8_to_s4_interp_bilinear): Upsample(scale_factor=2.0, mode='bilinear')
            (stack0_dec1_s8_to_s4_refine_conv0): Conv2d(192, 64, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_dec1_s8_to_s4_refine_conv0_act_relu): ReLU()
            (stack0_dec1_s8_to_s4_refine_conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_dec1_s8_to_s4_refine_conv1_act_relu): ReLU()
          )
        )
        (2): SimpleUpsamplingBlock(
          (blocks): Sequential(
            (stack0_dec2_s4_to_s2_interp_bilinear): Upsample(scale_factor=2.0, mode='bilinear')
            (stack0_dec2_s4_to_s2_refine_conv0): Conv2d(96, 32, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_dec2_s4_to_s2_refine_conv0_act_relu): ReLU()
            (stack0_dec2_s4_to_s2_refine_conv1): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=same)
            (stack0_dec2_s4_to_s2_refine_conv1_act_relu): ReLU()
          )
        )
      )
    )
  )
  (middle_blocks): ModuleList(
    (0): SimpleConvBlock(
      (blocks): Sequential(
        (stack0_enc5_middle_expand_conv0): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=same)
        (stack0_enc5_middle_expand_act0_relu): ReLU()
      )
    )
    (1): SimpleConvBlock(
      (blocks): Sequential(
        (stack0_enc6_middle_contract_conv0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=same)
        (stack0_enc6_middle_contract_act0_relu): ReLU()
      )
    )
  )
)
2026-03-24 14:38:50 | Head model: ModuleList(
  (0): Sequential(
    (CentroidConfmapsHead): Sequential(
      (0): Conv2d(32, 1, kernel_size=(1, 1), stride=(1, 1), padding=same)
      (1): Identity()
    )
  )
)
2026-03-24 14:38:50 | Total model parameters: 1,953,105
2026-03-24 14:38:51 | Input image shape: torch.Size([1, 1, 384, 512])
2026-03-24 14:39:54 | Finished trainer set up. [89.1s]
2026-03-24 14:39:54 | Starting training loop...
C:\Users\nalamlab\AppData\Roaming\uv\tools\sleap\Lib\site-packages\torch\__init__.py:1551: UserWarning: Please use the new API settings to control TF32 behavior, such as torch.backends.cudnn.conv.fp32_precision = 'tf32' or torch.backends.cuda.matmul.fp32_precision = 'ieee'. Old settings, e.g, torch.backends.cuda.matmul.allow_tf32 = True, torch.backends.cudnn.allow_tf32 = True, allowTF32CuDNN() and allowTF32CuBLAS() will be deprecated after Pytorch 2.9. Please see https://pytorch.org/docs/main/notes/cuda.html#tensorfloat-32-tf32-on-ampere-and-later-devices (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\Context.cpp:85.)
  return _C._get_float32_matmul_precision()
INFO: You are using a CUDA device ('NVIDIA RTX 4000 Ada Generation') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
INFO:lightning.pytorch.utilities.rank_zero:You are using a CUDA device ('NVIDIA RTX 4000 Ada Generation') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
C:\Users\nalamlab\AppData\Roaming\uv\tools\sleap\Lib\site-packages\lightning\pytorch\callbacks\model_checkpoint.py:881: Checkpoint directory C:\Users\nalamlab\Desktop\SLEAP_TRAINING\diet\models\fast_unet exists and is not empty.
INFO: LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
INFO:lightning.pytorch.accelerators.cuda:LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
┏━━━┳━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┓
┃   ┃ Name               ┃ Type         ┃ Params ┃ Mode  ┃ FLOPs ┃
┡━━━╇━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━┩
│ 0 │ model              │ Model        │  2.0 M │ train │     0 │
│ 1 │ centroid_inf_layer │ CentroidCrop │      0 │ train │     0 │
└───┴────────────────────┴──────────────┴────────┴───────┴───────┘
Trainable params: 2.0 M
Non-trainable params: 0
Total params: 2.0 M
Total estimated model params size (MB): 7
Modules in train mode: 73
Modules in eval mode: 0
Total FLOPs: 0
Sanity Checking DataLoader 0: 100%|██████████████████████████████████████████████████████| 2/2 [00:00<00:00,  4.93it/s]2026-03-24 14:39:54 | No predictions collected for centroid epoch-end evaluation
Epoch 0: 100%|██████████████████████████████████████████████████████████| 200/200 [00:08<00:00, 24.45it/s, loss=0.0075]2026-03-24 14:40:03 | Epoch 0 centroid evaluation: precision=0.0000, recall=0.0000, dist_avg=nanpx0:00<00:00, 24.23it/s]
Epoch 0: 100%|█████████████████████████████████████████| 200/200 [00:08<00:00, 23.59it/s, loss=0.0075, val/loss=0.0085]Polling: 
```

As you can see my GPU is detected, just not utilized, but things are training completely fine! Any suggestions on what the issue could be and how I could fix it? I can provide any additional info/logs/etc. upon request. 
-Daniel.

**Comment by dankunk** [comment]
I reverted back to sleap version 1.6.1 (sleap-io 0.6.4 and sleap-nn v0.1.0) and things are working on the GPU again. 

I'm still unsure what the issue was; however, the slp file that I saved with nodes removed is now working just fine on version 1.6.1.

Now, training a unet is utilizing the GPU significantly as I would expect and the CPU isn't nearing 100% utilization as before.

For anyone with the same issue I'd just suggest downloading the 1.6.2 version to make edits to the skeleton, save the slp file, then revert back to the stable release of 1.6.1 and keep working as normal.

**Comment by dankunk** [comment]
Circling back to this after messing with it a bit more and reading through some of the sleap output and PyTorch docs.

It looks like running in streaming / on-demand mode, or using cache-to-memory with num_workers=0, created a CPU bottleneck with the pytorch DataLoaders. In that case, my GPU was available and likely being minimally used, but it ends up underfed.

In my case, this seemed to explain the low GPU utilization / high CPU utilization pattern better than a true bug or issue with the 1.6.2 version.
